services:
  backend:
    build:
      context: .
      target: backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  frontend:
    build:
      context: .
      target: frontend
    env_file:
      - .env
    environment:
      FRONTEND_BACKEND_URL: http://backend:8000
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - backend
